name: Build

on:
  push:
    branches: [main, staging, dev-**]
  pull_request:
    branches: [main, staging, dev-**]

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: ["14", "16"]
    name: NodeJS v${{ matrix.node }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Latest Files
        uses: actions/checkout@v2
      - name: Initialize Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
